### ISSUE TITLE
How to setup if you don't use Powershell?

### ISSUE THREAD

**Issue by ciarancourtney** [winpax/sfsu#10]
For example, I use Git Bash's msys2 shell, so my scoop entrypoint is `~/scoop/shims/scoop`, so would I have to setup a bash alias to invoke the powershell hook, or is there a pure bash method of creating the hook?

**Comment by jewlexx** [comment]
I'm sure there is a bash way of doing it, which I can add, although I'm not 100% sure how it would be implemented, although I think it would be something like the following (although this would create an infinite loop).

```bash
function scoop {
  if $1 -eq "search"; then
    sfss.exe ${@:2}
  else
    scoop search ${@:2}
  fi
}
```

**Comment by ciarancourtney** [comment]
Ah I see, in that case I'll just remember to use the two binaries for now, I thought it had to hook into the powershell code directly.
