### ISSUE TITLE
Error: missing field `bucket` at line 5 column 1

### ISSUE THREAD

**Issue by brian6932** [winpax/sfsu#12]
![image](https://user-images.githubusercontent.com/18603393/202716310-31013965-8e01-4a8c-b22f-670b8d20fd16.png)
Is there some kind of debug logs that may help, or exporting my scoop buckets?

**Comment by jewlexx** [comment]
It looks like there is a `install.json` manifest file in one of your installed packages that is missing the bucket field. This would normally contain the bucket it was installed from. I am under the impression that said field should always exist but lmk if that is not the case. Regardless it would be best to add a special case for something like that, that doesn't completely end the process.

I am currently working on #13 which will help with debugging release builds.

**Comment by brian6932** [comment]
Yea I have a package that is `Source: <auto-generated>`, other than that every installed package has a bucket as source

**Comment by jewlexx** [comment]
If I may, what package is it? As far as I know, this isn't part of the [Scoop Manifest definition](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests), and if it isn't, I have no reason to work to support it. I look to add a case for when stuff like that panics, that doesn't exit the entire process however.

**Comment by brian6932** [comment]
> As far as I know, this isn't part of the [Scoop Manifest definition](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests)

It is, it's how installing specific versions are displayed.

If you specify a package version like `nodejs@19.0.1`, it will be set to `Source: <auto-generated>`.
https://github.com/ScoopInstaller/Scoop/issues/2254

Also another non-git way of installing packages would be locally installing a manifest json (`Source: pathToFile`), this should be supported as well ofc.

**Comment by jewlexx** [comment]
Fixed by #29
