### ISSUE TITLE
Make search pattern case-insensitive by default

### ISSUE THREAD

**Issue by shemanaev** [winpax/sfsu#2]
Native `scoop search` isn't case-sensitive, so it'll be better to align with its defaults when hooking.

**Comment by brian6932** [comment]
I noticed this as well
![image_10](https://user-images.githubusercontent.com/18603393/200205098-e03a4e37-9d0d-4fe4-b5cf-17ed2b48a2f1.png)

**Comment by jewlexx** [comment]
Will be added in the next release
