### ISSUE TITLE
sfsu hook failed to work

### ISSUE THREAD

**Issue by dnx04** [winpax/sfsu#223]
**Describe the bug**
I putted `Invoke-Expression (&sfsu hook)` to my $PROFILE, but PowerShell 5.1 failed to recognize it.

**To Reproduce**
1. `scoop install sfsu`.
2. Added sfsu to $PROFILE like the image below
![image](https://github.com/jewlexx/sfsu/assets/86938955/e63003f2-f131-43d5-9535-eb7082921602)
3. Exit and reenter PowerShell.
4. sfsu cannot be loaded and error is thrown.

**Expected behavior**
The hook should be set up, and all sfsu commands should be usable.

**Full Output**
If applicable, add the entire output to help our diagnosis of the problem.
![image](https://github.com/jewlexx/sfsu/assets/86938955/5c41ae13-eccd-4cf7-b65f-2be40093c3e5)

**Version [e.g. 1.4.8]**

**Comment by jewlexx** [comment]
I can't seem to replicate the issue, can you add the output from just calling the `sfsu hook` command and what version you are using please?

**Comment by dnx04** [comment]
I fixed it, thanks

**Comment by 2xG** [comment]
I have the same issue. @dnx04 can you please tell me how did you fix this?
For me `sfsu hook` command returns nothing. 

UPD Every command returns nothing, including `sfsu` without arguments.
version 1.9.1

**Comment by 2xG** [comment]
OK I fixed it too.
For those who have the same problem: this tool needs `vcredist` (Microsoft Visual C++ Redistributable) to be installed. I don't know which version exactly so I just installed all of them with `scoop install vcredist` and now all works as intended.
