### ISSUE TITLE
Invalid example for bash shown in readme

### ISSUE THREAD

**Issue by Yakiyo** [winpax/sfsu#228]
**Describe the bug**
The setup example for bash/zsh shown in the readme is wrong and doesnt work.

**To Reproduce**
- Run `sfsu hook --nix` as shown in the readme

**Expected behavior**
Akin to `hook --shell bash`
![image](https://github.com/jewlexx/sfsu/assets/91675932/f6e5601a-b5ee-4c1b-8ad8-5d041b3b6090)

**Full Output**
The output
![image](https://github.com/jewlexx/sfsu/assets/91675932/b96da64e-b2ed-497b-a338-d1054e73670d)

**Version - 1.4.8**

**Additional context**
Should be changed to `eval "$(sfsu hook --shell bash)"` or eval "\` sfsu hook --shell bash\` ". In all honesty, the command could just be something like `sfsu hook <SHELL>` where SHELL can be optional. Unless provided the app can just assume its on Powershell ig. Dont think theres any need to explicitly pass it as a flag. Since its more or less the only main argument to the subcommand but same thing.

**Comment by jewlexx** [comment]
> Unless provided the app can just assume its on Powershell ig.

That is currently what it does. If you just run sfsu hook it should print the powershell hook by default.

In terms of the other issue, I forgot to update the README for the new version, thanks for letting me know.
