### ISSUE TITLE
[ERROR] scoop search panic for certain inputs

### ISSUE THREAD

**Issue by RaphaelTarita** [winpax/sfsu#28]
I haven't found a pattern of which inputs fail and which don't, but when I, for example, try to do `scoop search a`, I get the following output:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', src/bin/search.rs:47:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', src/bin/search.rs:47:57
```

An example of an input that _does_ work would be `jdk` (funnily enough, `java` doesn't work)

All inputs work just fine for the original scoop implementation (other than being painfully slow)

**Comment by jewlexx** [comment]
Yeah thats really weird, I'll have a look ASAP

**Comment by jewlexx** [comment]
I've done some digging, and it looks like it panics when the bucket has a `.gitkeep` file in the bucket directory, which it shouldn't have, but for some reason the java bucket does have. I will open a PR there and fix the issue in the program as well.
