### ISSUE TITLE
`sfsu` doesn't consider the names of binaries inside a package unlike `scoop search`

### ISSUE THREAD

**Issue by arnabadas** [winpax/sfsu#391]
**Describe the bug**
`sfsu` doesn't consider the names of binaries inside a package unlike `scoop search`

**To Reproduce**
Run `scoop search sed` and `sfsu search sed`

**Expected behavior**
Both the commands should produce the same output

**Full Output**
`scoop search sed` yields the following output:
```powershell
Name                Version         Source Binaries
----                -------         ------ --------
msedgeredirect      0.7.5.0         extras
openclosedriveeject 3.21            extras
polsedit            1.0.0.5         extras
todolist            8.2.2           extras TDLTransEdit.exe
bazel-buildtools    6.3.3           main   unused_deps.exe
busybox             5181-g5c1a3b00e main   sed
djvulibre           3.5.28-4.12     main   djvused.exe
edgedriver          117.0.2045.47   main   msedgedriver.exe
gow                 0.8.0           main   sed.exe
pdf2djvu            0.9.19          main   djvused.exe
sed                 4.9             main
unxutils            2007.03.01      main   sed.exe
```

`sfsu search sed` yields the following output:
```powershell
'extras' bucket:
  msedgeredirect (0.7.5.0)
  openclosedriveeject (3.21)
  polsedit (1.0.0.5)

'main' bucket:
  sed (4.9)
```

**Version [e.g. 1.4.0]**
1.4.15

**Additional context**
The `gow` is a good package used for installing the `sed` but it doesn't show up when searching with `sfsu`. So this problem is very relevant.

**Comment by jewlexx** [comment]
This would be nice, but this could also incur massive slowdowns, as we'd need to parse every single manifest across every bucket.

I'll work on this, but I will probably put it behind a flag, so by default it is not enabled.

**Comment by arnabadas** [comment]
`scoop-search` does it by default and it is 6.5x slower than `sfsu` which is much better than the default search. Hence this feature should be prioritized.
