### ISSUE TITLE
<search:> `sfsu` search ignores binary names within packages

### ISSUE THREAD

**Issue by arnabadas** [winpax/sfsu#422]
#391 hasn't been fixed as of `sfsu` version `1.4.15`

**Comment by jewlexx** [comment]
Still waiting on #413 before I release it.

I don't have much time to work on this at the moment.
I'll get to it in about a week.

**Comment by jewlexx** [comment]
You can track the progress for the v1.5 release here: https://github.com/users/jewlexx/projects/6/views/1
