### ISSUE TITLE
Hook for nu: `extern-wrapped` is deprecated

### ISSUE THREAD

**Issue by wenxuanjun** [winpax/sfsu#441]
## Describe the bug

Command generated by `sfsu hook --shell nu` contains `extern-wrapped`, which is deprecated and will lead to warning.

```
Error:   × Deprecated command
   ╭─[sfsu.nu:1:1]
 1 │ extern-wrapped "scoop search" [...rest] { sfsu search $rest }
 2 │ extern-wrapped "scoop list" [...rest] { sfsu list $rest }
   · ───────┬──────
   ·        ╰── `extern-wrapped` is deprecated and will be removed in 0.88.
 3 │ extern-wrapped "scoop hook" [...rest] { sfsu hook $rest }
   ╰────
  help: Use `def --wrapped` instead
```

## Version

sfsu 1.5.1

**Comment by jewlexx** [comment]
It seems that `def --wrapped` currently [has some issues](https://github.com/nushell/nushell/issues/11096), specifically regarding help flags. 

As such, I'm not sure I can comfortably use it in production code.

I'll do some testing myself and follow up.
