### ISSUE TITLE
<list --ascending/descending:> Sort installed apps by date installed

### ISSUE THREAD

**Issue by MagicalDrizzle** [winpax/sfsu#506]
## Is your feature request related to a problem? Please describe

I want to see what apps I have recently installed.

## Describe the solution you'd like

Sort the installed app list by date installed. There's already a date column so this shouldn't be too hard.

**Comment by jewlexx** [comment]
I could add a `--sort-by` flag in conjunction with an `--ascending` flag to facilitate this, if that works for you?

**Comment by MagicalDrizzle** [comment]
That works for me. The argument I chose was more of a placeholder.
