### ISSUE TITLE
(probably) a stupid suggestion

### ISSUE THREAD

**Issue by ppvnf** [winpax/sfsu#54]
Thanks for this amazing script! Would you be interested in creating a CLI/package manager for Steam? There's this one called https://github.com/berenm/steam-cli, but it's missing a lot of features. Unfortunatelly I still barely know anything about programming, but at least I would help you test it out!

pun intended btw

**Comment by jewlexx** [comment]
No sorry, I don't really have any interest in creating such a program, and especially with Year 12, I'm not sure I have the free time to invest. 

Also next time please reach out on Discord, Twitter, etc. rather than Github Issues :)

P.S. Not a stupid question, this just isn't really the place
