### ISSUE TITLE
sfst-hook error

### ISSUE THREAD

**Issue by KememChan** [winpax/sfsu#55]
i add this `Invoke-Expression (&sfst-hook)` as instructed to $PROFILE after restarting it got this error, what happen?

```
Line |
   1 |  Invoke-Expression (&sfst-hook)
     |                      ~~~~~~~~~
     | The term 'sfst-hook' is not recognized as a name of a cmdlet, function, script file, or executable program.
     | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by jewlexx** [comment]
You will have to change the `sfst-hook` to `sfsu hook`.

In the [1.2.0](https://github.com/jewlexx/sfsu/releases/tag/v1.2.0) release I moved the entire program into a single binary, which replaced `sfst-hook` with `sfsu hook`. The note has been rectified in the manifest since.
