### ISSUE TITLE
sfsu update: concurrency bucket update

### ISSUE THREAD

**Issue by chocolatedesue** [winpax/sfsu#557]
As a strong supporter of Scoop, I've been considerably impressed by the robust performance of the SFSU implementation. It seamlessly combined the straightforwardness of Scoop with the blazing efficiency of Rust.

Currently, I've come across a potentially advantageous feature I believe SFSU could incorporate. Particularly, the addition of an update subcommand would enhance the tool's functionality and user experience.

In my understanding, this feature had been previously implemented by Hok, though it appears there hasn't been any recent update. 
Updating buckets with multiple repositories can be time-consuming , especially when using `scoop update -a`. 

By implementing this update subcommand, we could see a significant reduction in wait times.  I believe this could boost the overall efficiency of the tool and benefit all its users extensively.

**Comment by jewlexx** [comment]
This is [already planned](https://github.com/users/jewlexx/projects/5/views/1).

**Comment by chocolatedesue** [comment]
got it
