### ISSUE TITLE
`sfsu outdated` deprecated

### ISSUE THREAD

**Issue by sibouras** [winpax/sfsu#579]
i updated sfsu and i saw `sfsu outdated apps` is going to be removed, its alot faster than `sfsu status`, would be nice to keep it or have something similar to it

**Comment by jewlexx** [comment]
I'm trying to avoid haveing multiple commands that do the same thing, however I could add an `--only` flag, or something of the sort to `sfsu status` so it only checks the specific thing you need.

**Comment by sibouras** [comment]
that would be great thanks
