### ISSUE TITLE
`status`: Missing updates to global installed apps

### ISSUE THREAD

**Issue by MMKubicki** [winpax/sfsu#593]
## Describe the bug

The `status` command doesn't list any globally installed apps that have updates, while default `scoop status` does.

## Steps to To Reproduce

1. Have an outdated app installed globally/emulate it with custom bucket
2. Install & hook sfsu
3. Update manifest for globally installed app
4. run `scoop status` or `sfsu status` (same output)

## Expected behavior

Display available updates for globally installed apps like default `scoop status`.

Running without sfsu results in:
```pwsh
❯ scoop status
Scoop is up to date.

Name      Installed Version Latest Version Missing Dependencies Info
----      ----------------- -------------- -------------------- ----
llvm-test 17.0.6            18.1.2
```

## Full Output

```pwsh
❯ scoop status
Scoop app is up to date.
All buckets up to date.
All packages are okay and up to date.

❯ sfsu status
Scoop app is up to date.
All buckets up to date.
All packages are okay and up to date.
```

## Version

`1.9.2`

## Additional context
/

**Comment by jewlexx** [comment]
As per #442, sfsu does not yet have support for Scoop's global context, as I haven't really found a personal need for it yet.

Feel free to add a reaction or a comment to that issue if you want that to be a priority.
