### ISSUE TITLE
scoop hook arguments are broken

### ISSUE THREAD

**Issue by AtifChy** [winpax/sfsu#638]
## Describe the bug
![image](https://github.com/jewlexx/sfsu/assets/42291930/c5386ea0-ab4d-4b8d-b4fe-2f1188385a15)

## Steps to To Reproduce

1. run 'scoop checkup' 
2. See error

## Full Output

![image](https://github.com/jewlexx/sfsu/assets/42291930/5f03f08d-d8a0-4d8a-b920-9c57de483d27)

## Version
0.10.2

## Additional context
something happens with 'scoop status' command

**Comment by NotAsea** [comment]
@AtifChy i just found this issue too, look like she changed `sfsu hook` now it always requires at least one param to work.
For example :
```powershell
> scoop checkup
error: unexpected argument 'checkup' found

Usage: sfsu.exe checkup [OPTIONS]

For more information, try '--help'.
> scoop checkup ''
✅ Git is installed
✅ Main bucket is installed
✅ Windows Developer Mode is enabled
✅ Long paths are enabled
✅ NTFS is the filesystem of the Scoop directory
```
Which mean you need to pass something for it, empty string by `''` or `""`, in order it to work.
see more #639

**Comment by jewlexx** [comment]
It seems something is wrong with the Scoop hook, I'll have a look and fix this ASAP.

**Comment by jewlexx** [comment]
This should be fixed in the latest release.
Please re-open this issue if it isn't :P
