### ISSUE TITLE
Add feature to view app description like in scoop.sh

### ISSUE THREAD

**Issue by KememChan** [winpax/sfsu#65]
maybe if you scoop search only 1 result of the app it will show the description of that app on terminal, like for example i search "googlechrome" it will show the description of that app like below

![image](https://user-images.githubusercontent.com/47524544/213864141-c9dd41c9-8216-4452-bced-31c1c7d4cedc.png)

**Comment by jewlexx** [comment]
This is a good idea, although I think implementing it into the search would add unnecessary fluff. I will work on adding a seperate command, like `scoop describe` or something similar, which shows information like this.
