### ISSUE TITLE
Missing ")" after upgrading sfsu from 1.2.1 to 1.3.0

### ISSUE THREAD

**Issue by dertuxmalwieder** [winpax/sfsu#67]
PowerShell complains about my profile:

```
Line |
  15 |  Invoke-Expression (&sfsu hook)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Missing closing ')' in subexpression.
```

I guess something went wrong.

**Comment by drewbitt** [comment]
+1. Also docs are not clear, the message when installing says to use `&sfsu hook` while README says `&sfst-hook`, while of course neither work with this bug.

**Comment by dertuxmalwieder** [comment]
`&sfsu hook` is correct, it worked in 1.2.1...

**Comment by jewlexx** [comment]
Yeah sorry I am aware of this issue, I messed up something with the hook in the v1.3.0 release.



> +1. Also docs are not clear, the message when installing says to use `&sfsu hook` while README says `&sfst-hook`, while of course neither work with this bug.

Yeah readme is outdated thats my b

**Comment by jewlexx** [comment]
Fixed in the new version
