### ISSUE TITLE
`sfsu status --ignore-held` still displays held packages

### ISSUE THREAD

**Issue by mizzuri** [winpax/sfsu#712]
## Version

v1.11.0

## Additional context

I really appreciate your extremely fast implementation of the requested feature.

A screenshot of the issue:

![Screenshot 2024-05-05 122625](https://github.com/jewlexx/sfsu/assets/1288437/33ec0040-36a0-49d8-9765-6f071773dc6a)

Please let me know if you need further information.
Thank you.

**Comment by jewlexx** [comment]
Should be fixed in #713
