### ISSUE TITLE
sfsu hook panics

### ISSUE THREAD

**Issue by tdortman** [winpax/sfsu#746]
Since the update to 1.13 sfsu seems to crash every time it tries to register its hooks
```
"name" = "sfsu"
"operating_system" = "Windows 10.0.22635 (Windows 11 Professional) [64-bit]"
"crate_version" = """
1.13.0
sprinkles 1.13.0
branch:
tag:v1.13.0
commit_hash:efb0ffbb
build_time:2024-05-10 14:32:09 +00:00
build_env:rustc 1.78.0 (9b00956e5 2024-04-29),1.78.0-x86_64-pc-windows-msvc
libgit2:1.7.2"""
"explanation" = '''
Panic occurred in file 'crates\sprinkles\src\contexts\user.rs' at line 27
'''
"cause" = "called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Error(\"invalid type: null, expected path string\", line: 3, column: 19) }"
"method" = "Panic"
"backtrace" = """

   0: 0x7ff6eacac03a - <unresolved>
   1: 0x7ff6eaca541b - <unresolved>
   2: 0x7ff6eaa61b66 - <unresolved>
   3: 0x7ff6eacae0c5 - <unresolved>
   4: 0x7ff6eb4b348c - git_midx_writer_new
   5: 0x7ffe81f3257d - BaseThreadInitThunk
   6: 0x7ffe82d4aa48 - RtlUserThreadStart"""

```

**Comment by tdortman** [comment]
Actually, after looking into this a bit more it seems the config gets messed up when saving it after updating sometimes hmm

**Comment by jewlexx** [comment]
Is your scoop installed at the default location (~/scoop)?

Also, could you provide, if set, the value of your `SCOOP` environment variable?

I can't for the life of me figure out why it would get set to null. 

I'll merge your PR regardless because this should be something we can recover from.

**Comment by tdortman** [comment]
> Is your scoop installed at the default location (~/scoop)?

Yeah, it's under the home directory 

> Also, could you provide, if set, the value of your SCOOP environment variable?

Doesn't seem to be set to anything
