### ISSUE TITLE
sfsu can't find Scoop install

### ISSUE THREAD

**Issue by max7pro** [winpax/sfsu#759]
Hi! 
Please help. I used about six month about, but today I got error first time.
I attached screenshot and log file. Git doesn't allow to upload *.toml file, so I added txt extension.
Thank you in advance.

[report-7804a1f1-e1a7-4c6e-b1c3-2e20d7e91d4f.toml.txt](https://github.com/winpax/sfsu/files/15299791/report-7804a1f1-e1a7-4c6e-b1c3-2e20d7e91d4f.toml.txt)

![image](https://github.com/winpax/sfsu/assets/145686781/ce27bb35-1d70-4049-875a-af486bc82505)

**Comment by jewlexx** [comment]
It looks like sfsu can't find your Scoop install.

Can you tell me a few things:
1. Where your Scoop install is
2. Your scoop config (without sensitive details such as your virustotal api key if you have one)
3. The output of your SCOOP environment variable (i.e `echo $env:SCOOP` in PowerShell)

Thanks

**Comment by max7pro** [comment]
Thank you for your answer.
Scoop is my favourite package manager, any app I want to install I always check first if scoop repos have it. And after I meet your Sfsu app, I begun to use it always to control Scoop. It was working for long time, but suddenly stoped work yestrerady. So it is very important for me to run it again.


  1.
Scoop path is D:\Program Files\Scoop

[cid:cb40729c-cb8c-4aa4-b934-68add2ee037c]



  1.
Hope I am right regarding data you need about scoop config. I used config file and config command and both has few variables only.

[cid:76e707d3-7268-4e2b-aa85-191b8291b855]

  2.
echo $env:SCOOP doesn't output any data, means empty output

      [cid:5feff510-9007-4fb9-8918-1c1aa5ed915d]
________________________________

**Comment by max7pro** [comment]
Thank you for your answer.
Scoop is my favourite package manager, any app I want to install I always check first if scoop repos have it. And after I meet your Sfsu app, I begun to use it always to control Scoop. It was working for long time, but suddenly stoped work yestrerady. So it is very important for me to run it again.

1. Scoop path is D:\Program Files\Scoop

![image](https://github.com/winpax/sfsu/assets/145686781/9192ffac-a7db-4014-9c4f-bc6e370408a1)


2. Hope I am right regarding data you need about scoop config. I used config file and config command and both has few variables only.

![image](https://github.com/winpax/sfsu/assets/145686781/6b887fd2-bc2e-429b-beb8-68fc7e634246)

3. echo $env:SCOOP doesn't output any data, means empty output

![image](https://github.com/winpax/sfsu/assets/145686781/cd56df30-273a-4f00-9523-d21a302af961)

**Comment by max7pro** [comment]
> 3\. The output of your SCOOP environment variable (i.e `echo $env:SCOOP` in PowerShell)

Thank you for your help. After I sent you details you asked, I saw this variable is empty (I don't know why it was deleted) I understand that I must add SCOOP variable. Then I put it using Windows GUI ( sysdm.cpl ) and sfsu became working.
