### ISSUE TITLE
Error using any sfsu command

### ISSUE THREAD

**Issue by max7pro** [winpax/sfsu#832]
Hello! 
Thank you for app 👍 I like it very much.
But now I can't use it, because after last update I always receive error with each sfsu command I try to run.
I am attaching screenshot of error and log file. Please help to fix.

![image](https://github.com/winpax/sfsu/assets/145686781/23cd64a5-9a40-405c-96c3-d695938d2b38)

[report-c50f663a-5834-48ee-92cd-aa77f0fb82a1.toml.txt](https://github.com/user-attachments/files/15957964/report-c50f663a-5834-48ee-92cd-aa77f0fb82a1.toml.txt)

P. S. I added txt extension for log file, because github doesn't allow to attach toml file.

**Comment by jewlexx** [comment]
This seems to be the same issue as #824.

I'll look into why this keeps happening though.

(Also sorry for the late response I'm away at the minute)

**Comment by max7pro** [comment]
You are right. Solved. Thank you.
