### ISSUE TITLE
hooks: startsWith not working

### ISSUE THREAD

**Issue by brian6932** [winpax/sfsu#95]
**Describe the bug**
When hooks are not called, and `sfsu search` is used directly, the search is performed as startsWith (normal/expected behavior), but when a hook is used, and sfsu is called with `scoop search`, startsWith no longer works.

**To Reproduce**
1. Enable hooks
2. `sfsu search ...`
3. `scoop search ...`

**Expected behavior**
startsWith searching

**Full Output**

![image](https://user-images.githubusercontent.com/18603393/217510704-46bb2169-bc47-4c4c-be8a-d79e53f6be54.png)

**Version 1.4.2**

**Comment by jewlexx** [comment]
I've tested this locally using the same bucket, same version and same search command, and I can't seem to replicate the issue, so unfortunately there's not much I can do. I'll look in the code and see if there's anything that might trigger that, but without a source for the issue, its gonna be hard to fix it.

Is it only the `payload` query that breaks it? Or any query of that nature.

**Comment by brian6932** [comment]
![image](https://user-images.githubusercontent.com/18603393/217522664-cdc49af8-c181-4387-aa81-b13f570e0537.png)
for me it's happening with any query

**Comment by brian6932** [comment]
Ah this is my bad, I had an issue with my hooks, and didn't realize, sry for the trouble
